
dev/britannio/lox/Expr.java: dev/britannio/tool/GenerateAst.java
	javac -d . dev/britannio/tool/GenerateAst.java && java dev.britannio.tool.GenerateAst dev/britannio/lox/
	rm dev/britannio/tool/GenerateAst.class
