# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Jlox CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  jlox-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Run Verify Goal
      run: |
        cd jlox/
        mvn verify -X